name: Publish Documentation

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    permissions:
      checks: write # for actions/upload-artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install mkdocs mkdocs-material

      - name: Generate Docs
        run: ./scripts/build_docs.sh

      - uses: actions/upload-artifact@v4
        with:
          name: 'github-pages'
          path: site/

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
